language: node_js
node_js: stable

install:
  - npm install

script:
  - npm run docs:build

after_script:
  - cd ./dist
  - echo 'fs-calvin.com' > CNAME
  - git init
  - git config user.name "llb421270473"
  - git config user.email "421270473@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/llb421270473/Blog